## docker build -t onzyone/puppet-dev
## https://yum.puppetlabs.com/puppet5/el/7/x86_64/

FROM centos:7

# puppet 5.x
ENV PUPPET_AGENT_VERSION="5.5.1"
ENV PDK_VERSION="1.5.0.0"

# puppet modules
ENV PUPPET_MODULE_AZURE_VERSION="1.3.1"
ENV PUPPET_MODULE_STDLIB_VERSION="4.23.0"
ENV PUPPET_MODULE_AZUREMETADATA_VERSION="0.1.3"

# other version
ENV PACKER_VERSION="1.2.1"

# puppet agent and pdk
RUN rpm -Uvh https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
RUN yum install -y epel-release; yum upgrade -y; yum update -y
RUN yum install -y puppet-agent-"${PUPPET_AGENT_VERSION}"
RUN yum install -y pdk-"${PDK_VERSION}"

RUN rm -rf /etc/puppetlabs/puppet/hiera.yaml

# required for the gem files
RUN yum install -y bind-utils gcc gcc-c++ git-all libffi-devel net-tools python-devel python-pip python34 ruby-devel strace vim wget unzip zlib-devel zip && yum clean all

# Install the Azure CLI and boto3 for aws python interaction
WORKDIR /var/tmp/
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN /usr/bin/python get-pip.py
RUN /usr/bin/pip install azure-cli boto3

# puppet-azure requirments
RUN /opt/puppetlabs/puppet/bin/gem install retries --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install azure --version='~>0.7.0' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install azure_mgmt_compute --version='~>0.3.0' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install azure_mgmt_storage --version='~>0.3.0' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install azure_mgmt_resources --version='~>0.3.0' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install azure_mgmt_network --version='~>0.3.0' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install hocon --version='~>1.1.2' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install aws-sdk-core --no-ri --no-rdoc

ENV PATH=/opt/puppetlabs/server/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin:$PATH

RUN puppet module install puppetlabs-azure --version ${PUPPET_MODULE_AZURE_VERSION}
RUN puppet module install puppetlabs-stdlib --version ${PUPPET_MODULE_STDLIB_VERSION}
RUN puppet module install keirans-azuremetadata --version ${PUPPET_MODULE_AZUREMETADATA_VERSION}

# puppet strings for documentation of your modules
# https://github.com/puppetlabs/puppet-strings
RUN puppet resource package yard provider=puppet_gem
RUN puppet resource package puppet-strings provider=puppet_gem


# Install JQ
WORKDIR /usr/local/bin/
RUN wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
RUN mv jq-linux64 jq
RUN chmod 755 /usr/local/bin/jq

# Install Packer
RUN wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
RUN unzip packer_${PACKER_VERSION}_linux_amd64.zip
RUN rm packer_${PACKER_VERSION}_linux_amd64.zip

ENTRYPOINT [""]

CMD ["/bin/bash"]
# CMD ["agent", "--verbose", "--onetime", "--no-daemonize", "--summarize" ]
