# Need to ensure that you have built onzyone/puppet:latest. Found in the Dockerfile_puppet
## docker build -f Dockerfile_aws -t onzyone/aws-dev .

FROM onzyone/puppet:latest

#---------------------------------
# AWS puppet modules
#---------------------------------
ENV PUPPET_MODULE_AWS_VERSION="2.1.0"

RUN mkdir ~/.aws

#---------------------------------
# HASHICORP
#---------------------------------
ENV PACKER_VERSION="1.2.5"
ENV TERRAFORM_VERSION="0.11.10"
ENV TERRAGRUNT_VERSION="0.17.1"
ENV VAULT_VERSION="0.11.0"

#---------------------------------
# Install the AWS CLI Tools
#---------------------------------
RUN curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "/var/tmp/awscli-bundle.zip"
WORKDIR /var/tmp/
RUN unzip awscli-bundle.zip
WORKDIR /var/tmp/awscli-bundle/
RUN /var/tmp/awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
RUN rm -rf /var/tmp/awscli-bundle.zip /var/tmp/awscli-bundle

USER linuxbrew
RUN brew tap aws/tap
RUN brew install awscli
RUN brew install aws-sam-cli

USER root

#---------------------------------
# Install AWS ruby sdk
#---------------------------------
RUN gem install aws-sdk --no-ri --no-rdoc

#---------------------------------
# boto3 for aws python interaction
#---------------------------------
WORKDIR /var/tmp/
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN /usr/bin/python get-pip.py
RUN /usr/bin/pip install boto3

ENV PATH=/opt/puppetlabs/server/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin:/usr/local/go/bin:$PATH

#---------------------------------
# puppet module installs
#---------------------------------
RUN puppet module install puppetlabs-aws --version ${PUPPET_MODULE_AWS_VERSION}

WORKDIR /usr/local/bin/

#---------------------------------
# Install Packer
#---------------------------------
RUN wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
RUN unzip packer_${PACKER_VERSION}_linux_amd64.zip
RUN rm packer_${PACKER_VERSION}_linux_amd64.zip

#---------------------------------
# Install Terraform
#---------------------------------
RUN wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
RUN unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip
RUN rm terraform_${TERRAFORM_VERSION}_linux_amd64.zip

#---------------------------------
# Install Terragrunt ... good or bad ... it is what it is
#---------------------------------
RUN wget https://github.com/gruntwork-io/terragrunt/releases/download/v${TERRAGRUNT_VERSION}/terragrunt_linux_amd64
RUN mv terragrunt_linux_amd64 terragrunt
RUN chmod 755 terragrunt

#---------------------------------
# Install Vault
#---------------------------------
RUN wget https://releases.hashicorp.com/vault/${VAULT_VERSION}/vault_${VAULT_VERSION}_linux_amd64.zip
RUN unzip vault_${VAULT_VERSION}_linux_amd64.zip
RUN rm vault_${VAULT_VERSION}_linux_amd64.zip

# CMD ["agent", "--verbose", "--onetime", "--no-daemonize", "--summarize" ]
