## docker build -t onzyone/puppet-dev

FROM centos:7

# puppet 5.x
ENV PUPPET_AGENT_VERSION="5.5.1"
ENV PDK_VERSION="1.5.0.0"

# puppet modules
ENV PUPPET_MODULE_STDLIB_VERSION="4.23.0"
ENV PUPPET_MODULE_GOOGLE_CLOUD_VERSION="0.2.2"

# other version
ENV PACKER_VERSION="1.2.1"

# puppet agent and pdk
RUN rpm -Uvh https://yum.puppetlabs.com/puppet5/puppet5-release-el-7.noarch.rpm
RUN yum install -y epel-release; yum upgrade -y; yum update -y
RUN yum install -y puppet-agent-"${PUPPET_AGENT_VERSION}"
RUN yum install -y pdk-"${PDK_VERSION}"

RUN rm -rf /etc/puppetlabs/puppet/hiera.yaml

# required for the gem files
#RUN yum install -y python34-devel
RUN yum install -y bind-utils gcc gcc-c++ git-all libffi-devel net-tools python-devel python-pip ruby-devel strace vim wget unzip zlib-devel zip && yum clean all

# Install google cloud sdk

RUN echo [google-cloud-sdk]  > /etc/yum.repos.d/google-cloud-sdk.repo
RUN echo name=Google Cloud SDK >> /etc/yum.repos.d/google-cloud-sdk.repo
RUN echo baseurl=https://packages.cloud.google.com/yum/repos/cloud-sdk-el7-x86_64 >> /etc/yum.repos.d/google-cloud-sdk.repo
RUN echo enabled=1 >> /etc/yum.repos.d/google-cloud-sdk.repo
RUN echo gpgcheck=1 >> /etc/yum.repos.d/google-cloud-sdk.repo
RUN echo repo_gpgcheck=1 >> /etc/yum.repos.d/google-cloud-sdk.repo
RUN echo gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg \
       https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg >> /etc/yum.repos.d/google-cloud-sdk.repo

RUN yum -y install google-cloud-sdk

ENV PATH=/opt/puppetlabs/server/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin:$PATH

RUN puppet module install puppetlabs-stdlib --version ${PUPPET_MODULE_STDLIB_VERSION}
RUN puppet module install google-cloud --version ${PUPPET_MODULE_GOOGLE_CLOUD_VERSION}

# puppet strings for documentation of your modules
# https://github.com/puppetlabs/puppet-strings
RUN puppet resource package yard provider=puppet_gem
RUN puppet resource package puppet-strings provider=puppet_gem

# Install JQ
WORKDIR /usr/local/bin/
RUN wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
RUN mv jq-linux64 jq
RUN chmod 755 /usr/local/bin/jq

# Install Packer
RUN wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
RUN unzip packer_${PACKER_VERSION}_linux_amd64.zip
RUN rm packer_${PACKER_VERSION}_linux_amd64.zip

ENTRYPOINT [""]

CMD ["/bin/bash"]
# CMD ["agent", "--verbose", "--onetime", "--no-daemonize", "--summarize" ]
