## docker build -f Dockerfile_aws -t onzyone/puppet .
## https://yum.puppetlabs.com/puppet5/el/7/x86_64/
## https://yum.puppetlabs.com/puppet6/el/7/x86_64/

FROM centos:7

#---------------------------------
# puppet 6.x
#---------------------------------
ENV PUPPET_AGENT_VERSION="6.0.4"
ENV PDK_VERSION="1.7.1.0"
ENV PUPPET_BOLT_VERSION="1.3.0"

ENV PUPPET_MODULE_STDLIB_VERSION="5.1.0"

#---------------------------------
# GO Version
#---------------------------------
ENV GO_VERSION="1.11"

#---------------------------------
# JQ version
#---------------------------------
ENV JQ_VERSION="1.5"

#---------------------------------
# Base utils
#---------------------------------
RUN yum install -y \
    bind-utils \
    gcc \
    gcc-c++ \
    git-all \
    libffi-devel \
    net-tools \
    net-tools \
    python-devel \
    python-pip \
    python34 \
    python34-devel \
    ruby \
    ruby-devel \
    strace \
    tree \
    unzip \
    vim \
    wget \
    zip \
    zlib-devel

RUN yum clean all

#---------------------------------
# Install JQ
#---------------------------------
WORKDIR /usr/local/bin/
#RUN wget https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/jq-${JQ_VERSION}.tar.gz
#RUN mv jq-linux64 jq
#RUN chmod 755 /usr/local/bin/jq

#---------------------------------
# puppet agent, bolt and pdk
#---------------------------------
RUN rpm -Uvh https://yum.puppetlabs.com/puppet6/puppet6-release-el-7.noarch.rpm
RUN yum install -y epel-release; yum upgrade -y; yum update -y
RUN yum install -y pdk-"${PDK_VERSION}"
RUN yum install -y puppet-agent-"${PUPPET_AGENT_VERSION}"
RUN yum install -y puppet-bolt-"${PUPPET_BOLT_VERSION}"
RUN yum clean all

RUN rm -rf /etc/puppetlabs/puppet/hiera.yaml

ENV PATH=/opt/puppetlabs/server/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin:$PATH

RUN puppet module install puppetlabs-stdlib --version ${PUPPET_MODULE_STDLIB_VERSION}

# puppet strings for documentation of your modules
# https://github.com/puppetlabs/puppet-strings
RUN puppet resource package yard provider=puppet_gem
RUN puppet resource package puppet-strings provider=puppet_gem

#---------------------------------
# Install Golang
#---------------------------------
RUN wget https://dl.google.com/go/go${GO_VERSION}.linux-amd64.tar.gz
RUN tar -C /usr/local -xzf go${GO_VERSION}.linux-amd64.tar.gz
RUN rm go${GO_VERSION}.linux-amd64.tar.gz
ENV PATH=$PATH:/usr/local/go/bin

#---------------------------------
# install linuxbrew
#---------------------------------
RUN localedef -i en_US -f UTF-8 en_US.UTF-8 \
	&& useradd -m -s /bin/bash linuxbrew \
	&& echo 'linuxbrew ALL=(ALL) NOPASSWD:ALL' >>/etc/sudoers

USER linuxbrew
WORKDIR /home/linuxbrew

ENV PATH=/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:$PATH \
	SHELL=/bin/bash \
	USER=linuxbrew

RUN yes | ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install)" \
	&& brew config

RUN brew upgrade
RUN brew update

RUN brew install python

USER root