# Need to ensure that you have built onzyone/puppet:latest. Found in the Dockerfile_puppet
## docker build -t onzyone/puppet-dev
## https://yum.puppetlabs.com/puppet5/el/7/x86_64/

FROM onzyone/puppet:latest

# puppet modules
ENV PUPPET_MODULE_AZURE_VERSION="1.3.1"
ENV PUPPET_MODULE_AZUREMETADATA_VERSION="0.1.3"

# other version
ENV PACKER_VERSION="1.2.5"

# required for the gem files
RUN yum install -y bind-utils gcc gcc-c++ git-all libffi-devel net-tools python-devel python-pip python34 ruby-devel strace vim wget unzip zlib-devel zip && yum clean all

# Install the Azure CLI
WORKDIR /var/tmp/
RUN curl -O https://bootstrap.pypa.io/get-pip.py
RUN /usr/bin/python get-pip.py
RUN /usr/bin/pip install azure-cli

# puppet-azure requirments
RUN /opt/puppetlabs/puppet/bin/gem install retries --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install azure --version='~>0.7.0' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install azure_mgmt_compute --version='~>0.3.0' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install azure_mgmt_storage --version='~>0.3.0' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install azure_mgmt_resources --version='~>0.3.0' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install azure_mgmt_network --version='~>0.3.0' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install hocon --version='~>1.1.2' --no-ri --no-rdoc
RUN /opt/puppetlabs/puppet/bin/gem install aws-sdk-core --no-ri --no-rdoc

ENV PATH=/opt/puppetlabs/server/bin:/opt/puppetlabs/puppet/bin:/opt/puppetlabs/bin:$PATH

RUN puppet module install puppetlabs-azure --version ${PUPPET_MODULE_AZURE_VERSION}
RUN puppet module install keirans-azuremetadata --version ${PUPPET_MODULE_AZUREMETADATA_VERSION}

# Install Packer
RUN wget https://releases.hashicorp.com/packer/${PACKER_VERSION}/packer_${PACKER_VERSION}_linux_amd64.zip
RUN unzip packer_${PACKER_VERSION}_linux_amd64.zip
RUN rm packer_${PACKER_VERSION}_linux_amd64.zip

ENTRYPOINT [""]

CMD ["/bin/bash"]
# CMD ["agent", "--verbose", "--onetime", "--no-daemonize", "--summarize" ]
